version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.10-management
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - dss_network
  main:
    env_file:
      - envs/.main_env
    image: yakiroren/dss-main:latest
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
    networks:
      - dss_network
  uploader:
    env_file:
      - envs/.uploader_env
    restart: always
    image: yakiroren/dss-uploader:latest
    depends_on:
      - rabbitmq
    networks:
      - dss_network
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    env_file:
      - .env
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${ME_CONFIG_MONGODB_ADMINUSERNAME}:${ME_CONFIG_MONGODB_ADMINPASSWORD}@${MONGODB_URL}
    env_file:
      - .env


networks:
  dss_network:
