version: '3'
services:
#  mongo:
#    image: mongo
#    restart: unless-stopped
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
#    ports:
#      - 27017:27017
#    env_file:
#      - envs/.mongo_env
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    env_file:
      - envs/.mongo_env